### ISSUE TITLE
Create and test scrapy spider for motor.es

### ISSUE THREAD

**Issue by eliseobao** [eliseobao/carggregator#2]
1. Open new branch with:

 ```sh
git flow feature start Issue-2
```

2. Create and test scrapy spider for [motor.es](https://www.motor.es/coches-segunda-mano/)

**Tasks:** 

- [x] Create basic spider
- [x] Scrape a few items
- [x] Postprocess (clean) items
