### ISSUE TITLE
Create and test scrapy spider for Flexicar

### ISSUE THREAD

**Issue by eliseobao** [eliseobao/carggregator#3]
1. Open new branch with:

```sh
git flow feature start Issue-3
```

2. Create and test scrapy spider for [Flexicar](https://www.flexicar.es/coches-segunda-mano/)

**Tasks:** 

- [x] Create basic spider
- [x] Scrape a few items
- [ ] Postprocess (clean) items

**Comment by agr17** [comment]
Feature cancelada
