### ISSUE TITLE
Create and test scrapy spider for Autocasion

### ISSUE THREAD

**Issue by eliseobao** [eliseobao/carggregator#4]
1. Open new branch with:

```sh
git flow feature start Issue-4
```

2. Create and test scrapy spider for [Autocasion](https://www.autocasion.com/coches-ocasion)

**Tasks:** 

- [x] Create basic spider
- [x] Scrape a few items
- [x] Postprocess (clean) items

**Comment by agr17** [comment]
Ready.
